### ISSUE TITLE
PROCESO DE NEGOCIO

### ISSUE THREAD

**Issue by Vanessacruzortiz** [SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-equipo-v-a-k#1]
[MODELO DE NEGOCIO EN BIZAGI.pdf](https://github.com/user-attachments/files/17181540/MODELO.DE.NEGOCIO.EN.BIZAGI.pdf)

**Comment by edgarmauricio123** [comment]
Después de que lo corrigieron Cumple con los requisitos de la rubrica 20 de 20, por lo tanto esta vez cumple con los requisitos

**Comment by josealfredo79** [comment]
No se puede evaluar...NO ES UN PROCESO DE NEGOCIO @edgarmauricio123 Favor de checar...

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
